# ------------------------------------------------------------
# finapp.local
# ------------------------------------------------------------



map $scheme $hsts_header {
    https   "max-age=63072000; preload";
}

server {
  set $forward_scheme http;
  set $server         "my-appfin-front-service";
  set $port           8100;

  listen 80;
listen [::]:80;


  server_name finapp.local;
http2 off;











proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection $http_connection;
proxy_http_version 1.1;


  access_log /data/logs/proxy-host-5_access.log proxy;
  error_log /data/logs/proxy-host-5_error.log warn;

# Configuration principale (Angular + API)
location / {
    proxy_pass http://my-appfin-front-service:8100;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
}

# Configuration spécifique pour le WebSocket avec le préfixe du contrôleur
location /backfront/ws {
    proxy_pass http://my-appfin-front-service:8100;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $host;
    
    # Paramètres critiques pour SockJS
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    
    # On désactive le cache et le buffering pour le temps réel
    proxy_cache_bypass $http_upgrade;
    proxy_buffering off;
    proxy_read_timeout 86400;
}





  # Custom
  include /data/nginx/custom/server_proxy[.]conf;
}
