version: '3.8'
services:

  traefik:
    image: traefik:v3.6.2
    container_name: traefik
    command:
      - "--api=true"
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.traefik.address=:8090"
    ports:
      - "80:80"
      - "8090:8090"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - spring-cloud-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=PathPrefix(`/api`) || PathPrefix(`/dashboard`)"
      - "traefik.http.routers.dashboard.entrypoints=traefik"
      - "traefik.http.routers.dashboard.service=api@internal"

  server-db:
    image: postgres
    container_name: myfinappdbpostgres2
    volumes:
      - myfinappvolume:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: myfinappdb
      POSTGRES_USER: admin
    ports:
      - "8300:5432"
    depends_on:
      - traefik
    networks:
      - spring-cloud-network

  eureka-server:
    image: smrp1111/my-eureka-service:latest
    depends_on:
      - server-db
    networks:
      - spring-cloud-network

  gateway-service:
    image: smrp1111/my-gateway-service:latest
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka-server:8761/eureka"
    depends_on:
      - eureka-server
    networks:
      - spring-cloud-network
    labels:
      - "traefik.enable=true"
      - 'traefik.http.routers.gateway.rule=Host("api.finapp.local")'
      - "traefik.http.services.gateway.loadbalancer.server.port=8888"
      
  my-appfin-back-service:
    image: smrp1111/my-appfin-back-service:latest
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka-server:8761/eureka"
      DB_URL: "jdbc:postgresql://server-db:5432/myfinappdb"
      DB_USER: "admin"
      DB_PASSWORD: "1234"
    depends_on:
      - gateway-service
    networks:
      - spring-cloud-network
      
  my-appfin-batch-service:
    image: smrp1111/my-appfin-batch-service:latest
    environment:
      BASEREFGATE_BACKSERVICE: "http://gateway-service:8888/MYFINAPPBACKSERVICE"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka-server:8761/eureka"
    depends_on:
      - my-appfin-back-service
    networks:
      - spring-cloud-network
      
  my-appfin-front-service:
    image: smrp1111/my-appfin-front-service:latest
    ports:
      - "8100:8100"
    environment:
      APP_TEST: "MON TESSSSSSSSSSSSSSSSSSSSSSSSSST"  
      SERVER_PORT: 8100 
      BASEREFGATE_BACKSERVICE: "http://gateway-service:8888/MYFINAPPBACKSERVICE"
      BASEREFGATE_BATCHSERVICE: "http://gateway-service:8888/MYFINAPPBATCHSERVICE" 
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka-server:8761/eureka"
    depends_on:
      - my-appfin-batch-service
    networks:
      - spring-cloud-network
    labels:
      - "traefik.enable=true"
      - 'traefik.http.routers.front.rule=Host("finapp.local")'
      - "traefik.http.services.front.loadbalancer.server.port=8100"
      

volumes:
  myfinappvolume:
  nginx_data:
  nginx_letsencrypt:

networks:
  spring-cloud-network:
    driver: bridge