server.port=8100

# 1. On importe le DOSSIER (configtree crée des variables à partir des noms de fichiers)
#spring.config.import=optional:configtree:/run/secrets/


app_base_ref_gateway_back_service=${BASEREFGATE_BACKSERVICE:http://localhost:8889/MYFINAPPBACKSERVICE}

app_base_ref_gateway_batch_service=${BASEREFGATE_BATCHSERVICE:http://localhost:8889/MYFINAPPBATCHSERVICE}

spring.web.resources.static-locations=classpath:/static/

spring.cloud.config.enabled=true

#spring.config.import=configserver:http://localhost:8888/MYFINAPPCONFIGSERVICE/ # ne marche pas mais marche si envoyé depuis docker compose

# Expose l'endpoint health
management.endpoints.web.exposure.include=health
# Permet d'avoir plus de détails (optionnel)
management.endpoint.health.show-details=always