/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.psi.myfinappfrontapp.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * AccountDateSumDTO
 */
@JsonPropertyOrder({
  AccountDateSumDTO.JSON_PROPERTY_CUURENCY,
  AccountDateSumDTO.JSON_PROPERTY_MONTH,
  AccountDateSumDTO.JSON_PROPERTY_SUM,
  AccountDateSumDTO.JSON_PROPERTY_YEAR
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-15T16:56:00.367694300+01:00[Europe/Paris]", comments = "Generator version: 7.12.0")
public class AccountDateSumDTO implements Serializable {
  private static final long serialVersionUID = 1L;

  /**
   * Gets or Sets cuurency
   */
  public enum CuurencyEnum {
    EUR(String.valueOf("EUR")),
    
    USD(String.valueOf("USD"));

    private String value;

    CuurencyEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static CuurencyEnum fromValue(String value) {
      for (CuurencyEnum b : CuurencyEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_CUURENCY = "cuurency";
  @jakarta.annotation.Nullable
  private CuurencyEnum cuurency;

  public static final String JSON_PROPERTY_MONTH = "month";
  @jakarta.annotation.Nullable
  private Integer month;

  public static final String JSON_PROPERTY_SUM = "sum";
  @jakarta.annotation.Nullable
  private BigDecimal sum;

  public static final String JSON_PROPERTY_YEAR = "year";
  @jakarta.annotation.Nullable
  private Integer year;

  public AccountDateSumDTO() {
  }

  public AccountDateSumDTO cuurency(@jakarta.annotation.Nullable CuurencyEnum cuurency) {
    
    this.cuurency = cuurency;
    return this;
  }

  /**
   * Get cuurency
   * @return cuurency
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CUURENCY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CuurencyEnum getCuurency() {
    return cuurency;
  }


  @JsonProperty(JSON_PROPERTY_CUURENCY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCuurency(@jakarta.annotation.Nullable CuurencyEnum cuurency) {
    this.cuurency = cuurency;
  }

  public AccountDateSumDTO month(@jakarta.annotation.Nullable Integer month) {
    
    this.month = month;
    return this;
  }

  /**
   * Get month
   * @return month
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MONTH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getMonth() {
    return month;
  }


  @JsonProperty(JSON_PROPERTY_MONTH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMonth(@jakarta.annotation.Nullable Integer month) {
    this.month = month;
  }

  public AccountDateSumDTO sum(@jakarta.annotation.Nullable BigDecimal sum) {
    
    this.sum = sum;
    return this;
  }

  /**
   * Get sum
   * @return sum
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getSum() {
    return sum;
  }


  @JsonProperty(JSON_PROPERTY_SUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSum(@jakarta.annotation.Nullable BigDecimal sum) {
    this.sum = sum;
  }

  public AccountDateSumDTO year(@jakarta.annotation.Nullable Integer year) {
    
    this.year = year;
    return this;
  }

  /**
   * Get year
   * @return year
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_YEAR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getYear() {
    return year;
  }


  @JsonProperty(JSON_PROPERTY_YEAR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setYear(@jakarta.annotation.Nullable Integer year) {
    this.year = year;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AccountDateSumDTO accountDateSumDTO = (AccountDateSumDTO) o;
    return Objects.equals(this.cuurency, accountDateSumDTO.cuurency) &&
        Objects.equals(this.month, accountDateSumDTO.month) &&
        Objects.equals(this.sum, accountDateSumDTO.sum) &&
        Objects.equals(this.year, accountDateSumDTO.year);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cuurency, month, sum, year);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AccountDateSumDTO {\n");
    sb.append("    cuurency: ").append(toIndentedString(cuurency)).append("\n");
    sb.append("    month: ").append(toIndentedString(month)).append("\n");
    sb.append("    sum: ").append(toIndentedString(sum)).append("\n");
    sb.append("    year: ").append(toIndentedString(year)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

