/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.psi.myfinappfrontapp.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.LocalDate;
import org.psi.myfinappfrontapp.model.AmountOfMoney;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * AccountLineDTO
 */
@JsonPropertyOrder({
  AccountLineDTO.JSON_PROPERTY_DATE,
  AccountLineDTO.JSON_PROPERTY_SOLDE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-15T16:56:00.367694300+01:00[Europe/Paris]", comments = "Generator version: 7.12.0")
public class AccountLineDTO implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_DATE = "date";
  @jakarta.annotation.Nullable
  private LocalDate date;

  public static final String JSON_PROPERTY_SOLDE = "solde";
  @jakarta.annotation.Nullable
  private AmountOfMoney solde;

  public AccountLineDTO() {
  }

  public AccountLineDTO date(@jakarta.annotation.Nullable LocalDate date) {
    
    this.date = date;
    return this;
  }

  /**
   * Get date
   * @return date
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public LocalDate getDate() {
    return date;
  }


  @JsonProperty(JSON_PROPERTY_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDate(@jakarta.annotation.Nullable LocalDate date) {
    this.date = date;
  }

  public AccountLineDTO solde(@jakarta.annotation.Nullable AmountOfMoney solde) {
    
    this.solde = solde;
    return this;
  }

  /**
   * Get solde
   * @return solde
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SOLDE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AmountOfMoney getSolde() {
    return solde;
  }


  @JsonProperty(JSON_PROPERTY_SOLDE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSolde(@jakarta.annotation.Nullable AmountOfMoney solde) {
    this.solde = solde;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AccountLineDTO accountLineDTO = (AccountLineDTO) o;
    return Objects.equals(this.date, accountLineDTO.date) &&
        Objects.equals(this.solde, accountLineDTO.solde);
  }

  @Override
  public int hashCode() {
    return Objects.hash(date, solde);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AccountLineDTO {\n");
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    solde: ").append(toIndentedString(solde)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

